package org.springsteps.services;

import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springsteps.domain.Inquiry;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@SpringBootTest
class InquirySpringJdbcDaoIT {

  @Autowired
  InquirySpringJdbcDao inquiryRepository;

  /**
   * Save simple database entity.
   *
   * <p>Id generated by database.
   */
  @Test
  void testSaveInquiry_withEmail_withoutId() {
    String email = "test101@example.org";

    var inquiry = new Inquiry();
    inquiry.setEmail(email);

    assertThat(inquiry.getId()).isNull();

    Inquiry savedInquiry = inquiryRepository.save(inquiry);

    assertThat(inquiry.getId()).isNotNull();

    UUID generatedIdByDb = savedInquiry.getId();
    assertThat(generatedIdByDb).isNotNull();

    var loadedInquiry = inquiryRepository
        .findInquiryByEmailAndPhoneNumber(email, null)
        .getFirst();

    assertThat(loadedInquiry).isEqualTo(savedInquiry);
  }

  /**
   * Save simple database entity.
   *
   * <p>Id generated by database.
   */
  @Test
  void testSaveInquiry_withPhoneNumber_withoutId() {
    String phoneNumber = "+421800500600#test102";

    var inquiry = new Inquiry();
    inquiry.setPhoneNumber(phoneNumber);

    assertThat(inquiry.getId()).isNull();

    Inquiry savedInquiry = inquiryRepository.save(inquiry);

    assertThat(inquiry.getId()).isNotNull();

    UUID generatedIdByDb = savedInquiry.getId();
    assertThat(generatedIdByDb).isNotNull();

    var loadedInquiry = inquiryRepository
        .findInquiryByEmailAndPhoneNumber(null, phoneNumber)
        .getFirst();

    assertThat(loadedInquiry).isEqualTo(savedInquiry);
  }

  /**
   * Save database entity with all data.
   *
   * <p>Id generated by database.
   */
  @Test
  void testSaveInquiry_allData_withoutId() {
    String email = "test103@example.org";
    String phoneNumber = "+421 700 103 103";

    var inquiry = new Inquiry();
    inquiry.setFullName("Test 103");
    inquiry.setEmail(email);
    inquiry.setPhoneNumber(phoneNumber);
    inquiry.setText("Test inquiry #103.");

    assertThat(inquiry.getId()).isNull();

    Inquiry savedInquiry = inquiryRepository.save(inquiry);

    assertThat(inquiry.getId()).isNotNull();

    UUID generatedIdByDb = savedInquiry.getId();
    assertThat(generatedIdByDb).isNotNull();

    List<Inquiry> results = inquiryRepository.findInquiryByEmailAndPhoneNumber(email, phoneNumber);

    assertThat(results).hasSize(1);

    var loadedInquiry = results.getFirst();

    assertThat(loadedInquiry).isEqualTo(savedInquiry);
  }

  /**
   * Test required_minimum_data database constraint.
   *
   * <p>An inquiry must contain at least an email or a phone number to be processed.
   */
  @Test
  void testSaveInquiry_withoutEmailAndPhoneNumber() {
    var inquiry = new Inquiry();
    assertThat(inquiry.getId()).isNull();

    assertThatExceptionOfType(DataIntegrityViolationException.class)
        .isThrownBy(() -> inquiryRepository.save(inquiry))
        .withMessageContaining("violates check constraint \"required_minimum_data\"");
  }

  @Test
  void testSaveInquiry_update() {
    var textBeforeUpdate = "Test inquiry #120.";
    var textAfterUpdate = "Test inquiry #120 updated.";

    var inquiry =
        inquiryRepository.findInquiryByEmailAndPhoneNumber("test120@example.org", null).getFirst();

    assertThat(inquiry.getId()).isNotNull();
    assertThat(inquiry.getText()).isEqualTo(textBeforeUpdate);

    UUID inquiryIdBeforeUpdate = inquiry.getId();

    // Update inquiry.

    inquiry.setText(textAfterUpdate);
    inquiryRepository.save(inquiry);

    assertThat(inquiry.getId()).isEqualTo(inquiryIdBeforeUpdate);

    // Verify updated inquiry by loading it from database again.

    List<Inquiry> results =
        inquiryRepository.findInquiryByEmailAndPhoneNumber("test120@example.org", null);

    assertThat(results).hasSize(1);

    var updatedInquiry = results.getFirst();

    assertThat(updatedInquiry.getId()).isEqualTo(inquiryIdBeforeUpdate);
    assertThat(updatedInquiry.getEmail()).isEqualTo(inquiry.getEmail());
    assertThat(updatedInquiry.getFullName()).isEqualTo(inquiry.getFullName());
    assertThat(updatedInquiry.getPhoneNumber()).isEqualTo(inquiry.getPhoneNumber());
    assertThat(updatedInquiry.getText()).isEqualTo(textAfterUpdate);
  }

  @Test
  void testFindInquiryByEmailAndPhoneNumber() {
    var email = "test110@example.org";
    var phoneNumber = "0900 110 110";

    List<Inquiry> results = inquiryRepository.findInquiryByEmailAndPhoneNumber(email, phoneNumber);

    assertThat(results).hasSize(1);

    var inquiryResult = results.getFirst();

    assertThat(inquiryResult.getId()).isNotNull();
    assertThat(inquiryResult.getEmail()).isEqualTo(email);
    assertThat(inquiryResult.getPhoneNumber()).isEqualTo(phoneNumber);
    assertThat(inquiryResult.getFullName()).isEqualTo("Test 110");
  }

  @Test
  void testFindInquiryByEmailAndPhoneNumber_onlyByEmail() {
    var email = "test111@example.org";

    List<Inquiry> results = inquiryRepository.findInquiryByEmailAndPhoneNumber(email, null);

    assertThat(results).hasSize(1);

    var inquiryResult = results.getFirst();

    assertThat(inquiryResult.getId()).isNotNull();
    assertThat(inquiryResult.getEmail()).isEqualTo(email);
    assertThat(inquiryResult.getPhoneNumber()).isNull();
    assertThat(inquiryResult.getFullName()).isEqualTo("Test 111");
  }

  @Test
  void testFindInquiryByEmailAndPhoneNumber_onlyByPhoneNumber() {
    var phoneNumber = "0900 112 112";

    List<Inquiry> results = inquiryRepository.findInquiryByEmailAndPhoneNumber(null, phoneNumber);

    assertThat(results).hasSize(1);

    var inquiryResult = results.getFirst();

    assertThat(inquiryResult.getId()).isNotNull();
    assertThat(inquiryResult.getEmail()).isNull();
    assertThat(inquiryResult.getPhoneNumber()).isEqualTo(phoneNumber);
    assertThat(inquiryResult.getFullName()).isEqualTo("Test 112");
  }
}